version: "3.3"
# Указываем раздел со связанными сервисами

services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: abobus123

  nginx:
    depends_on:
      - frontend
      - backend
    image: nginx:latest
    expose:
      - '80'
    volumes:
      # Используем свой nginx конфиг, он заменит дефолтный в контейнере
      - ./nginx:/etc/nginx/conf.d
      # Монтируем папку с логами на хост машину для более удобного доступа
      - ./logs:/var/log/nginx/
    restart: always

  frontend:
    build: ./oopl45s4_front
    expose:
      - '3000'
    restart: always

  backend:
    depends_on:
      - db
    build: ./oopl45s4_back
    expose:
      - '8080'
    restart: always
    volumes:
      - ./appsettings.json:/app/appsettings.json

